### ISSUE TITLE
Some problems about the 3D track

### ISSUE THREAD

**Issue by alvin528** [HarveyW5678/-WarpingError_Floorplan#3]
Hello, I met some problems when I was doing 3d tasks. I raised an issue on GitHub, but I did not receive a reply. 
[https://github.com/arkhodakov/cvpr-2022-matching/issues/3](url)
As time is tight, could you please help deal with it (or tell the person in charge of the 3D task)? Thank you very much!

**Comment by HarveyW5678** [comment]
Hi

For the second question, the default rotation angle is 0.

You will receive a reply about your first question shortly, but I tested
the evaluation code with the ground truth file and got perfect results.

Have a nice day

**Comment by alvin528** [comment]
Thank you for your testing! 

If the internal distribution of two point clouds is the same (ground truth VS ground truth), point cloud registration using CPD method (rigid transformation) is effective. However, for Scan2BIM, the predicted results (the internal distribution of bounding boxes' vertices) are difficult to be same with ground truth. In such cases, point cloud registration (which is not stable) introduces additional errors that cause alignment coordinates to shift.

If we can find a stable error in the registration task of "Bounding boxes" point clouds, there won't be too much error introduced. But since the coordinates of the two point clouds are already aligned, registration doesn't seem that important.

Best wishes

**Comment by HarveyW5678** [comment]
Hi

The server has just been updated. Feel free to ask me any questions here.

Have a great day
